// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © veryfid

//@version=4
study("Volatility Oscillator", resolution = "")
length = input(100)
spike = close - open
x = stdev(spike,length)
y = stdev(spike,length) * -1

plot(spike, color = color.white, linewidth = 2, title = "Spike Line")

p1 = plot(x, "Upper Line")
p2 = plot(y, "Lower Line")

plot(0, color= color.gray, title= "Zero Line")
