FROM freqtradeorg/freqtrade:develop_plot

# Switch user to root if you must install something from apt
# Don't forget to switch the user back below!
# USER root

# The below dependency - pyti - serves as an example. Please use whatever you need!
RUN pip install --user pyti
RUN pip install --user ta
RUN pip install --user scikit-optimize

# USER ftuser
